# Use a Node.js base image. You can specify a version, e.g., node:18-slim
FROM mcr.microsoft.com/devcontainers/javascript-node:20-bullseye

# Set the working directory inside the container
WORKDIR /workspaces/my-nodejs-app
